version: '3.4'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    container_name: app
    build: .
    command: python -m uvicorn tasks:app --host 0.0.0.0 --port 8000 --reload
    # Mount the fast-celery folder into /app/fast-celery
    # Also mount the sibling assetsInfo folder into /app/assetsInfo
    volumes:
      - .:/app/fast-celery
      - ../assetsInfo:/app/assetsInfo
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - redis

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A celery_worker worker --pool=solo --loglevel=info
    volumes:
      - .:/app/fast-celery
      - ../assetsInfo:/app/assetsInfo
    depends_on:
      - redis
      - app

  flower:
    container_name: flower
    build: .
    command: celery -A celery_worker flower --port=5555
    ports:
      - "5556:5555"
    depends_on:
      - app
      - redis
      - celery_worker
